name: Build

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]
  merge_group:

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - build: ubuntu-22.04
          os: ubuntu-22.04
        - build: ubuntu-24.04
          os: ubuntu-24.04
        - build: macos
          os: macos-latest
        - build: windows
          os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - run: eng/build.sh
      shell: bash
    - uses: actions/upload-artifact@v4
      if: matrix.os == 'windows-latest'
      with:
        name: ${{ matrix.build }}
        path: target/release/az-pim.exe
        if-no-files-found: error
    - uses: actions/upload-artifact@v4
      if: matrix.os == 'macos-latest'
      with:
        name: ${{ matrix.build }}
        path: target/release/az-pim
        if-no-files-found: error
    - uses: actions/upload-artifact@v4
      if: startsWith(matrix.os, 'ubuntu-')
      with:
        name: ${{ matrix.build }}
        path: target/debian/*.deb
        if-no-files-found: error
  
  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - uses: softprops/action-gh-release@v2
        with:
          draft: true
          fail_on_unmatched_files: true
          files: |
            az-pim
            az-pim.exe
            *.deb
