name: Build

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]
  merge_group:

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - build: ubuntu-22.04
          os: ubuntu-22.04
        - build: ubuntu-24.04
          os: ubuntu-24.04
        - build: macos
          os: macos-latest
        - build: windows
          os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - run: eng/build.sh
      shell: bash
    - uses: actions/upload-artifact@v4
      if: matrix.os == 'windows-latest'
      with:
        name: ${{ matrix.build }}
        path: target/release/az-pim.exe
        if-no-files-found: error
    - uses: actions/upload-artifact@v4
      if: matrix.os == 'macos-latest'
      with:
        name: ${{ matrix.build }}
        path: target/release/az-pim
        if-no-files-found: error
    - uses: actions/upload-artifact@v4
      if: startsWith(matrix.os, 'ubuntu-')
      with:
        name: ${{ matrix.build }}
        path: target/debian/*.deb
        if-no-files-found: error
  
  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - run: find artifacts
      - name: Get the release version from the tag
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: show version
        run: |
          echo "version is: $VERSION"
      - name: Check that tag version and Cargo.toml version are the same
        shell: bash
        run: |
          if ! grep -q "version = \"$VERSION\"" Cargo.toml; then
            echo "version does not match Cargo.toml" >&2
            exit 1
          fi
      - name: rename artifacts
        run: |
          set -ex
          mv artifacts/macos/az-pim artifacts/macos/az-pim-macos
          mv artifacts/windows/az-pim.exe artifacts/windows/az-pim-windows.exe
          for ubuntu_rev in 22.04 24.04; do
            for file in artifacts/ubuntu-${ubuntu_rev}/*.deb; do
              mv "$file" "${file%.deb}_${ubuntu_rev}.deb"
            done
          done
          find artifacts
      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -ex
          gh release create $VERSION --draft --verify-tag --title $VERSION
          gh release upload $version $(find artifacts -type f)
